Fixed sufficient color contrast
camicroscope/caMicroscope pull request #1035
Opened 2024-08-25 14:45 UTC by Priyankagarai

Closes https://github.com/camicroscope/caMicroscope/issues/1034

Element is having low color contrast issue, I have made necessary modifications with font style to meet sufficient color contrast.

2024-10-11 17:27 UTC, birm commented
Hi and thank you for opening this PR!

Can you open a report or something stating that this fixes color contrast? It doesn't look to me like you're changing color at all.

A list of tools can be found here: https://www.w3.org/WAI/test-evaluate/tools/list/

2024-10-11 17:28 UTC, birm requested changes
Hi and thank you for opening this PR!

Can you open a report or something stating that this fixes color contrast? It doesn't look to me like you're changing color at all.

A list of tools can be found here: https://www.w3.org/WAI/test-evaluate/tools/list/

2024-10-12 05:44 UTC, Priyankagarai commented
Hi, thank you for your feedback!

I’ve tested the page using Lighthouse in Chrome DevTools. Initially, Lighthouse flagged poor color contrast (as shown before the fix), but after correcting the colors, the issue no longer appears, meaning the contrast now meets the accessibility standards.
Since Lighthouse doesn’t display warnings once the issue is fixed, there’s no message in the updated report. 

Let me know if further clarification is needed!

2024-10-31 17:55 UTC, birm approved these changes

2024-10-31 17:56 UTC, merged