[New Feature] Screenshot of Slide
camicroscope/caMicroscope pull request #496
Opened 2021-02-19 03:04 UTC by Hemansh31

## Description
**Describe your changes in detail

This screenshot feature helps user to take screenshot of the slide along with annotations and download it as an image.

## Motivation and Context
*Why is this change required? What problem does it solve?

This is useful as screenshots of slides are required by several users as they need to be included in reports or research papers.
Note :
This is the first and basic version of screen capture. Next step in this includes adding functionality to capture only a selected area of the slide.
This is the same PR as #493 

## How Has This Been Tested?
**Please describe in detail how you tested your changes.

I tested it on my local setup

## Screenshots (if appropriate):

![Untitled_ Feb 19, 2021 8_32 AM](https://user-images.githubusercontent.com/48997514/108451627-29ab9d00-728d-11eb-8fe6-44b6f5d9f179.gif)

## Types of changes
**What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
**Go over all the following points, and put an `x` in all the boxes that apply.
**(If you're unsure about any of these, don't hesitate to ask. We're here to help!)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-02-19 05:48 UTC, birm requested changes
If you can, could you add a record to the readme, as this is a new button. Also, I think this warrants a history.md addition, but if you don't want to add it now, I'll add it at the next release.

Thank you @Hemansh31, I'm sure people will like this addition!

2021-02-19 06:14 UTC, Hemansh31 commented
@birm I have updated the Readme.md file and History.md file

2021-02-19 06:15 UTC, birm approved these changes

2021-02-21 22:34 UTC, nanli-emory approved these changes
WOW ~~~~ a nice new feature, thanks @Hemansh31

2021-02-22 01:02 UTC, merged