smartpen milestone-1
camicroscope/caMicroscope pull request #526
Opened 2021-06-13 07:07 UTC by r7rohan

## Smartpen Milestone 1 #523
### Contains
- A simple version of smartpen feature, contains 2 working modes and a good UI, also contains other functions like undo, settings.
- Improvements for enhance feature (increase in speed to within a sec)

I have added the feature to annotations and preset label. This can be extended to anyother tab easily. I tested it, it works well. It supports any kind of annotations (freestyle, rectangles etc).

![2021-06-11-13-21-49-online-video-cuttercom_LwYa89D7_RAjt](https://user-images.githubusercontent.com/18577165/121743999-dac99200-cb1f-11eb-857a-96dd480e7136.gif)

### Code details
Written the edge detection in `enhance.js`. Written the smartpen class in `autoalign.js`, `autoalign.css`. Integrated the code in `openseadragon-canvas-draw-overlay`, added it to viewer in `uicallbacks.js`

### To dos
- Increase accuracy
- Increase speed

Feel free to provide suggestions, improvements, contributions related to the implementation or UI. And please review

2021-06-16 17:19 UTC, Insiyaa requested changes

2021-06-16 17:19 UTC, Insiyaa commented on apps/viewer/uicallbacks.js
> +          return;}
I have a lil issue with the placing of the closing curly brace `}`, everything else looks good!

2021-06-22 11:50 UTC, r7rohan commented on apps/heatmap/heatmap.html
> +	  <script type="text/javascript" src="../../common/smartpen/autoalign.js"></script>
Actually the smartpen is a part of openseadragon-canvas-draw-overlay. Currently, even if not used, the file has to be included with it. Haven't explored the heatmaps section, but if there is any need, smartpen can be activated with a line of code.

2021-06-23 20:02 UTC, birm approved these changes

2021-06-29 15:50 UTC, Insiyaa approved these changes

2021-06-29 16:07 UTC, merged