ui buttons changes
camicroscope/caMicroscope pull request #652
Opened 2023-08-25 10:41 UTC by amanjr09-glitch

The relaod and upload buttons are now seperate

2023-08-25 15:22 UTC, birm requested changes
Hi and thanks for submitting a PR! I have just a few comments, and I've changed the target branch from "master" to "develop".

2023-08-25 15:22 UTC, birm commented on HISTORY.md
> +### fix
Please add this as a bullet point in the latest "unreleased" code.

2023-08-28 06:19 UTC, amanjr09-glitch commented
can you please elaborate a little more

2024-02-05 06:27 UTC, MrunalKashid02 commented
can i PR for this because i want customize this buttons

2024-04-24 17:43 UTC, closed without merging