Fixed bug from #757 , added showdown library and converted markdown to html in workbench.js
camicroscope/caMicroscope pull request #759
Opened 2024-03-13 11:08 UTC by hannyP

### fixed the bug

 I am an outreachy 2024 applicant and found this issue while running the project on my local machine  

## Testing
it hasn't been tested as only UI elements were being tested in the repo.

## Questions
I used the showdown library to solve this issue , let me know if i shouldn't have used any library do tackle this issue

2024-03-13 11:20 UTC, hannyP commented
now when you click on help in workbench tab it should display the user guide like this
![Screenshot 2024-03-13 164941](https://github.com/camicroscope/caMicroscope/assets/141145167/f17b0953-4a98-45e9-9b79-bcde49d282b3)

2024-03-22 03:31 UTC, birm requested changes
Just one change and I think It'll look good!

2024-03-22 03:31 UTC, birm commented on .vscode/settings.json
> +{
Please don't include setting/config files for editors in PRs.

2024-04-24 17:49 UTC, birm commented on .vscode/settings.json
> +}
```suggestion
```

2024-04-24 17:54 UTC, birm commented
turns out to be fixed with #683

2024-04-24 17:54 UTC, closed without merging