Solved - Issue #741 Upload model form on view page needs adjustment o…
camicroscope/caMicroscope pull request #788
Opened 2024-03-17 07:20 UTC by HRIDYANSHU054

…n mobile view

## Summary
More Details. Added media queries to handle this in components\modalbox\modalbox.css 

## Motivation
Previous version of the modal form was not adapting well to mobile screens discouraging the application usage on mobile devices.

## Testing
The responsiveness testing was done using chrome developer tools
Following are the results
![tabletUIDistorted](https://github.com/camicroscope/caMicroscope/assets/124202756/cd030fcc-dd3d-4329-97ef-96d03b24f1ea)
Tablet UI Distortion

![tabletUIsolved](https://github.com/camicroscope/caMicroscope/assets/124202756/115edb11-c217-4229-9deb-fdc0b9f0c955)
Tablet UI solved

![mobileUIDistorted](https://github.com/camicroscope/caMicroscope/assets/124202756/29d7bd6e-ec2e-44a6-84f1-c75df28c9259)
Mobile UI Distortion

![mobileUIsolved](https://github.com/camicroscope/caMicroscope/assets/124202756/f0f31e84-01ba-4b9e-aead-fc36230a43e5)
Mobile UI solved

![desktopUI](https://github.com/camicroscope/caMicroscope/assets/124202756/d6b34286-cfc6-485b-9387-14b51373f6ce)
Desktop UI

2024-03-26 14:31 UTC, birm requested changes
This seems like a good idea, but I can't get it to actually render as expected without these "important" rules

2024-03-26 14:31 UTC, birm commented on components/modalbox/modalbox.css
> +        width: 85%;
```suggestion
        width: 85% !important;
```

2024-03-26 14:31 UTC, birm commented on components/modalbox/modalbox.css
> +        width: 50%;
```suggestion
        width: 50% !important;
```

2024-03-26 19:39 UTC, HRIDYANSHU054 commented
@birm I appreciate that you brought this to my notice this was blunder on my end. Please check now.

2024-04-24 14:39 UTC, birm approved these changes
That did it! Thank you!

2024-04-24 14:40 UTC, merged